# Generated by Django 5.0.3 on 2024-03-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_delete_entregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('profesor', models.CharField(max_length=60)),
                ('cantidad_alumnos', models.IntegerField()),
            ],
        ),
    ]
